"""Audio pointers on Weekly Thing issue records, and the graph the site gets.

Plan 2026-09-29 Phase 3 items 6 and 7. The audio record lives only in the
weekly site's archive page frontmatter; the build stamps issue records with
`audio: {url, duration_seconds, chapters: [{start, title}]}` and never lets it
near chunk text or the embedding input. The site's graph is the one built
from the embedded corpus, so its `similar_issues` are real.
"""

from __future__ import annotations

import gzip
import importlib.util
import json
import sys
from pathlib import Path
from unittest import mock

import pytest
from librarian_core import audio
from librarian_core.corpus import _embed_input, build_corpus
from librarian_core.paths import REPO

DEPLOY = REPO / "pipeline" / "deploy"


def _load(name: str, path: Path):
    spec = importlib.util.spec_from_file_location(name, path)
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


upload = _load("test_audio_upload_corpus", DEPLOY / "upload_corpus.py")
push_graph = _load("test_audio_push_graph", DEPLOY / "push_graph.py")

AUDIO_URL = "https://files.thingelstad.com/weekly-thing/351/weekly-thing-351-82e8257b.mp3"
CHAPTER_ONLY_TITLE = "Chapter Marker Zebra"
THINGY_QUESTION = "What has Jamie taken from Ethan Mollick's writing on AI?"

WITH_AUDIO = f"""---
layout: layouts/issue.njk
number: 351
subject: WT351 - Attention Is The Scarce Part
permalink: /archive/351/
audio_url: {AUDIO_URL}
audio_duration_seconds: 854
audio_byte_size: 22142241
audio_voice: openai-tts-1-hd:echo+nova
audio_chapters_url: https://files.thingelstad.com/weekly-thing/351/x.chapters.json
audio_transcript_url: https://files.thingelstad.com/weekly-thing/351/x.vtt
audio_chapters:
- start: 0
  title: Welcome
  url: 'https://weekly.thingelstad.com/archive/351/'
- start: 51.827
  title: {CHAPTER_ONLY_TITLE}
  image: 'https://files.thingelstad.com/weekly-thing/351/chapters/a.jpg'
- start: 779.001
  title: Echoes
- start: 808.589
  title: "{THINGY_QUESTION}"
  url: 'https://thingy.thingelstad.com/chat/?prompt=x&from=weekly-thing-351'
- start: not-a-number
  title: Broken start
- start: 900
- just a string
---
<!-- Generated by WT Builder (npm run rerender:archive) from data/issues; do not edit directly. -->
Body the corpus never reads from here.
"""

WITHOUT_AUDIO = """---
layout: layouts/issue.njk
number: 350
subject: WT350
permalink: /archive/350/
---
Body.
"""

MALFORMED = """---
number: 349
audio_url: [unclosed
---
Body.
"""


def _site(root: Path) -> Path:
    site = root / "apps" / "site" / "archive"
    site.mkdir(parents=True)
    (site / "351.md").write_text(WITH_AUDIO, encoding="utf-8")
    (site / "350.md").write_text(WITHOUT_AUDIO, encoding="utf-8")
    (site / "349.md").write_text(MALFORMED, encoding="utf-8")
    (site / "348.md").write_text("No frontmatter at all.\n", encoding="utf-8")
    return site


def _archive(root: Path) -> Path:
    archive = root / "issues"
    for number, topic in ((351, "attention"), (350, "agents"), (349, "rails"), (348, "cats")):
        (archive / str(number)).mkdir(parents=True)
        (archive / str(number) / "archive.md").write_text(
            f"---\nnumber: {number}\nsubject: Weekly Thing {number}\n"
            "publish_date: '2026-09-26T12:00:00Z'\n---\n"
            f"Intro about {topic}.\n\n## Notable\n\nA long thought about {topic}.\n",
            encoding="utf-8",
        )
    return archive


def _empty_site_dir(root: Path) -> Path:
    site = root / "site"
    (site / "_data").mkdir(parents=True)
    return site


def _corpus(root: Path) -> dict:
    return build_corpus(
        _archive(root),
        include_issue_bodies=True,
        site_dir=_empty_site_dir(root),
        faq_path=root / "missing-faq.json",
    )


def _issue(corpus: dict, number: int) -> dict:
    return next(issue for issue in corpus["issues"] if str(issue["number"]) == str(number))


def test_issue_with_audio_gets_the_pointer_and_chapters_trimmed(tmp_path):
    corpus = {"issues": [{"number": 351}]}

    assert audio.annotate_issue_audio(corpus, _site(tmp_path)) == 1

    assert corpus["issues"][0]["audio"] == {
        "url": AUDIO_URL,
        "duration_seconds": 854,
        "chapters": [
            {"start": 0, "title": "Welcome"},
            {"start": 51.827, "title": CHAPTER_ONLY_TITLE},
            {"start": 779.001, "title": "Echoes"},
        ],
    }


def test_thingy_echoes_questions_never_become_chapters(tmp_path):
    corpus = {"issues": [{"number": 351}]}
    audio.annotate_issue_audio(corpus, _site(tmp_path))

    titles = [chapter["title"] for chapter in corpus["issues"][0]["audio"]["chapters"]]
    assert THINGY_QUESTION not in titles
    assert "thingy.thingelstad.com" not in json.dumps(corpus)


def test_transcript_vtt_and_page_only_keys_stay_out(tmp_path):
    corpus = {"issues": [{"number": 351}]}
    audio.annotate_issue_audio(corpus, _site(tmp_path))

    shipped = json.dumps(corpus)
    for absent in (".vtt", "chapters.json", "22142241", "openai-tts", "chapters/a.jpg"):
        assert absent not in shipped


def test_issue_without_audio_and_malformed_pages_ship_without_audio(tmp_path, capsys):
    corpus = {"issues": [{"number": n} for n in (350, 349, 348, 347)]}

    assert audio.annotate_issue_audio(corpus, _site(tmp_path)) == 0

    assert all("audio" not in issue for issue in corpus["issues"])
    assert "skipped 2 site pages with unreadable frontmatter" in capsys.readouterr().out


def test_missing_site_dir_merges_nothing_and_never_fails(tmp_path, capsys):
    corpus = {"issues": [{"number": 351}]}

    assert audio.annotate_issue_audio(corpus, tmp_path / "no-such-checkout") == 0

    assert corpus == {"issues": [{"number": 351}]}
    assert "no weekly site archive" in capsys.readouterr().out


def test_default_dir_is_the_sibling_checkout_or_the_env_override(monkeypatch, tmp_path):
    monkeypatch.delenv(audio.SITE_ARCHIVE_ENV, raising=False)
    assert audio.default_site_archive_dir() == (
        REPO.parent / "weekly.thingelstad.com" / "apps" / "site" / "archive"
    )

    monkeypatch.setenv(audio.SITE_ARCHIVE_ENV, str(tmp_path))
    assert audio.default_site_archive_dir() == tmp_path


def test_audio_rides_the_issue_record_never_chunks_or_embed_input(tmp_path):
    plain = _corpus(tmp_path / "plain")
    corpus = _corpus(tmp_path / "with-audio")

    assert audio.annotate_issue_audio(corpus, _site(tmp_path)) == 1
    assert _issue(corpus, 351)["audio"]["url"] == AUDIO_URL

    for chunk in corpus["chunks"]:
        assert "audio" not in chunk
        for text in (chunk.get("text") or "", _embed_input(chunk)):
            assert AUDIO_URL not in text
            assert CHAPTER_ONLY_TITLE not in text
    # Chunk ids and embed inputs are byte-identical: the embedding cache stays warm.
    assert [(c["id"], _embed_input(c)) for c in corpus["chunks"]] == [
        (c["id"], _embed_input(c)) for c in plain["chunks"]
    ]


def test_production_build_stamps_audio(tmp_path):
    site = _site(tmp_path)
    corpus = upload.build_wt_corpus(
        _archive(tmp_path),
        tmp_path / "no-sidecar.json",
        site_archive_dir=site,
        site_dir=_empty_site_dir(tmp_path),
        faq_path=tmp_path / "missing-faq.json",
    )

    assert _issue(corpus, 351)["audio"]["duration_seconds"] == 854
    assert "audio" not in _issue(corpus, 350)


def test_production_build_without_the_site_still_builds(tmp_path):
    corpus = upload.build_wt_corpus(
        _archive(tmp_path),
        tmp_path / "no-sidecar.json",
        site_archive_dir=tmp_path / "absent",
        site_dir=_empty_site_dir(tmp_path),
        faq_path=tmp_path / "missing-faq.json",
    )

    assert len(corpus["issues"]) == 4
    assert all("audio" not in issue for issue in corpus["issues"])


# --- Item 6: the site's graph carries real similar_issues ---


def _fake_embed(corpus, *_args, **_kwargs):
    for index, chunk in enumerate(corpus["chunks"]):
        chunk["embedding"] = [1.0, float(index % 3), 0.5]


def test_uploaded_graph_is_built_from_the_embedded_corpus(tmp_path):
    uploaded: dict[str, dict] = {}

    def capture(_bucket, key, path):
        uploaded[key] = json.loads(Path(path).read_text(encoding="utf-8"))

    argv = ["upload_corpus.py", "--bucket", "b", "--key", "artifacts/corpus.json"]
    with (
        mock.patch.object(upload, "ARCHIVE_DIR", _archive(tmp_path)),
        mock.patch.object(upload, "MEDIA_DESCRIPTIONS_PATH", tmp_path / "none.json"),
        mock.patch.dict("os.environ", {audio.SITE_ARCHIVE_ENV: str(tmp_path / "absent")}),
        mock.patch.object(upload, "load_dotenv"),
        mock.patch.object(upload, "fetch_existing_corpus", return_value=None),
        mock.patch.object(upload, "add_bedrock_embeddings", side_effect=_fake_embed),
        mock.patch.object(upload, "upload_json_gzip", side_effect=capture),
        mock.patch.object(sys, "argv", argv),
    ):
        assert upload.main() == 0

    graph = uploaded["artifacts/graph.json"]
    assert set(graph["issues"]) == {"348", "349", "350", "351"}
    assert all(issue["similar_issues"] for issue in graph["issues"].values())
    assert "None" not in graph["issues"]


GRAPH = {
    "version": 1,
    "issues": {
        "1": {"entities": [], "tropes": [], "similar_issues": [{"number": "2", "score": 0.9}]},
        "2": {"entities": [], "tropes": [], "similar_issues": [{"number": "1", "score": 0.9}]},
    },
}


class _S3:
    def __init__(self, body: bytes):
        self.body = body
        self.calls: list[tuple[str, str]] = []

    def get_object(self, Bucket, Key):
        self.calls.append((Bucket, Key))
        return {"Body": mock.Mock(read=mock.Mock(return_value=self.body))}


def _run_push(argv: list[str], s3: _S3, **patches):
    with (
        mock.patch.object(push_graph.boto3, "client", return_value=s3),
        mock.patch.object(sys, "argv", ["push_graph.py", *argv]),
        mock.patch.multiple(push_graph.github_repo, **patches),
    ):
        return push_graph.main()


def test_handoff_pushes_the_s3_graph_not_the_local_file(tmp_path):
    s3 = _S3(gzip.compress(json.dumps(GRAPH).encode()))
    # The pre-embedding graph a local build leaves behind: no similar_issues.
    stale_local = tmp_path / "data" / "librarian" / "graph.json"
    stale_local.parent.mkdir(parents=True)
    stale_local.write_text(json.dumps({"issues": {"1": {"similar_issues": []}}}))
    put_tree = mock.Mock(return_value="abc1234def")

    with (
        mock.patch.object(push_graph, "REPO_ROOT", tmp_path),
        mock.patch.object(push_graph, "GRAPH", stale_local),
    ):
        assert _run_push(["--from-s3", "--push"], s3, put_tree=put_tree) == 0

    assert s3.calls == [("weekly-thing-librarian", "artifacts/graph.json")]
    (files, message), kwargs = put_tree.call_args
    [(path, content)] = files
    assert path == "data/librarian/graph.json"
    assert json.loads(content) == GRAPH
    # Written the way pipeline/graph/build.py writes it, so site diffs stay readable.
    assert content == (json.dumps(GRAPH, ensure_ascii=False, indent=2) + "\n").encode()


def test_handoff_dry_run_from_s3_reads_plain_json_too(capsys):
    s3 = _S3(json.dumps(GRAPH).encode())
    get = mock.Mock(return_value={"tree": []})

    assert _run_push(["--from-s3"], s3, _get=get, _repo=mock.Mock(return_value="o/r")) == 0

    out = capsys.readouterr().out
    assert "similar_issues on 2 of 2 issues" in out
    assert "graph.json added" in out


def test_handoff_pushes_nothing_when_the_s3_graph_cannot_be_read():
    s3 = _S3(b"not json")
    put_tree = mock.Mock()

    with pytest.raises(json.JSONDecodeError):
        _run_push(["--from-s3", "--push"], s3, put_tree=put_tree)
    put_tree.assert_not_called()
