"""Build a citation-ready corpus for the archive librarian.

Reads ``data/issues/{N}/archive.md``, splits each issue into chunks with
topic/section metadata, and (optionally) calls Bedrock Cohere to embed every
chunk. The resulting dict is JSON-serializable and is consumed by Thingy and
the graph builder.
"""

from __future__ import annotations

import hashlib
import json
import re
from dataclasses import dataclass
from datetime import datetime, timezone
from pathlib import Path
from typing import Any
from urllib.parse import urljoin, urlparse

import boto3
import yaml
from dotenv import load_dotenv

from .links import extract_domains, link_label_text, markdown_links, section_family, unlink
from .paths import ARCHIVE_DIR, BLOG_DIR, FAQ_PATH, PODCAST_DIR, SITE_DIR

DEFAULT_EMBEDDING_MODEL = "cohere.embed-english-v3"
DEFAULT_EMBEDDING_DIMENSIONS = 1024
COHERE_EMBED_MAX_TEXT_CHARS = 2048
GENERATED_NOTICE_RE = re.compile(
    r"^<!-- Generated by (?:scripts/content|pipeline/content/content)\.py.*?-->\s*", re.S
)
FRONTMATTER_RE = re.compile(r"^---\s*\n(.*?)\n---\s*\n?", re.S)
TEMPLATE_LEAK_RE = re.compile(
    r"({%\s*|{{\s*|buttondown-editor-mode|Generated by (?:scripts/content|pipeline/content/content)\.py)",
    re.I,
)
HEADING_RE = re.compile(r"^(#{1,4})\s+(.+?)\s*$", re.M)
WORD_RE = re.compile(r"[A-Za-z0-9][A-Za-z0-9'\-]*")
SENTENCE_RE = re.compile(r"(?<=[.!?])\s+")
TOPIC_KEYWORDS = {
    "AI and agents": {
        "ai",
        "agent",
        "agents",
        "openai",
        "claude",
        "llm",
        "gpt",
        "model",
        "models",
        "prompt",
    },
    "Open web and RSS": {
        "rss",
        "feed",
        "feeds",
        "blog",
        "blogs",
        "website",
        "web",
        "podcast",
        "tapestry",
    },
    "Privacy and security": {
        "privacy",
        "security",
        "secure",
        "token",
        "tokens",
        "password",
        "surveillance",
        "encryption",
    },
    "Productivity and systems": {
        "productivity",
        "omnifocus",
        "gtd",
        "workflow",
        "calendar",
        "tasks",
        "method",
    },
    "IndieWeb and personal sites": {
        "indieweb",
        "microblog",
        "activitypub",
        "fediverse",
        "ownyourdata",
    },
    "Travel and place": {
        "travel",
        "banff",
        "lake",
        "trip",
        "hotel",
        "museum",
        "landscape",
        "airport",
        "europe",
        "city",
    },
    "Media and culture": {
        "book",
        "books",
        "movie",
        "film",
        "music",
        "media",
        "culture",
        "streaming",
        "podcast",
    },
    "Software development": {
        "software",
        "code",
        "developer",
        "development",
        "github",
        "api",
        "programming",
        "server",
    },
    "Crypto and web3": {
        "bitcoin",
        "crypto",
        "ethereum",
        "nft",
        "poap",
        "token",
        "tokens",
        "wallet",
        "web3",
    },
}
EVERGREEN_SECTIONS = {"essay", "journal", "issue", "briefly", "currently"}


def issue_sort_key(value: Any) -> tuple[int, str]:
    text = str(value)
    match = re.match(r"(\d+)", text)
    if not match:
        return (10**9, text)
    return (int(match.group(1)), text)


def read_issue(path: Path) -> tuple[dict[str, Any], str]:
    text = path.read_text(encoding="utf-8")
    text = GENERATED_NOTICE_RE.sub("", text)
    match = FRONTMATTER_RE.match(text)
    if not match:
        raise RuntimeError(f"{path} is missing YAML front matter")
    metadata = yaml.safe_load(match.group(1)) or {}
    body = GENERATED_NOTICE_RE.sub("", text[match.end() :]).strip()
    return metadata, body


# Thingy's bylined blocks (Echoes, Membership) are framed by WT Builder as
# <div class="from-thingy"> + label <p> + markdown + </div> on its own line
# (wt-builder src/shared/render/website.ts). They are Thingy's words, not
# Jamie's, so the corpus never sees them: no chunk, count, topic, link or
# summary is built from them. The frame is a cross-repo contract, pinned by
# tests here and in wt-builder tests/echoes.test.ts.
THINGY_BLOCK_RE = re.compile(r'<div class="from-thingy">.*?\n</div>[ \t]*\n?', re.S)


def strip_thingy_blocks(body: str) -> str:
    stripped = THINGY_BLOCK_RE.sub("", body)
    if stripped == body:
        return body
    return re.sub(r"\n{3,}", "\n\n", _drop_emptied_headings(stripped))


def _drop_emptied_headings(body: str) -> str:
    """Drop a heading the Thingy strip left with nothing under it (WB frames
    Echoes as "## Echoes" plus the block), so get_source bodies don't end on
    a bare heading. A heading followed by a deeper one is not empty."""
    matches = list(HEADING_RE.finditer(body))
    spans = []
    for index, match in enumerate(matches):
        following = matches[index + 1] if index + 1 < len(matches) else None
        end = following.start() if following else len(body)
        if body[match.end() : end].strip():
            continue
        if following is None or len(following.group(1)) <= len(match.group(1)):
            spans.append((match.start(), end))
    for start, end in reversed(spans):
        body = body[:start] + body[end:]
    return body.rstrip() + "\n" if spans else body


def clean_heading(value: str) -> str:
    # The scanner, not a "[^\]]" regex, so "[Python post-Guido [LWN.net]](url)"
    # is the title and not the raw markdown (QA 2026-09-30, links L7).
    value = unlink(value)
    value = re.sub(r"[*_`#]+", "", value)
    return " ".join(value.split())


@dataclass(frozen=True)
class IssueSection:
    """One split section of an issue body. ``heading`` is the section's own
    heading (a Notable item's H3 title, or the H2 itself); ``parent`` is the
    enclosing H1/H2 heading and ``family`` that H2's era-independent family
    (``links.section_family``), so "Microposts 🎈" and "Journal" are both
    Journal. ``raw_heading`` keeps the heading's markdown, links and all."""

    heading: str
    family: str
    parent: str
    text: str
    raw_heading: str = ""


def split_issue_sections(body: str) -> list[IssueSection]:
    """Split on H1-H4 like ``split_sections``, carrying each section's H2 and
    family. Text before the first heading is the "Issue" intro, family Intro.
    An H2 missing from the family map is its own family, except after a
    group header: a known H2 with no text of its own followed straight by
    another H2 (the 2018 "Links 📌" over "Tech", "Business", ...), whose
    family the unlisted H2s under it share."""
    matches = list(HEADING_RE.finditer(body))
    if not matches:
        return [IssueSection("Issue", "Intro", "Issue", body.strip())]

    sections: list[IssueSection] = []
    if matches[0].start() > 0:
        intro = body[: matches[0].start()].strip()
        if intro:
            sections.append(IssueSection("Issue", "Intro", "Issue", intro))

    parent, family, group = "Issue", "Intro", None
    for index, match in enumerate(matches):
        following = matches[index + 1] if index + 1 < len(matches) else None
        end = following.start() if following else len(body)
        section_body = body[match.end() : end].strip()
        heading = clean_heading(match.group(2))
        if len(match.group(1)) <= 2:
            parent = heading
            known = section_family(heading)
            if known:
                family = known
                opens_group = following is not None and len(following.group(1)) <= 2
                if not section_body and opens_group:
                    group = known
                elif known != group:
                    group = None
            else:
                family = group or heading
        if section_body:
            sections.append(IssueSection(heading, family, parent, section_body, match.group(2)))
    return sections


def split_sections(body: str) -> list[tuple[str, str]]:
    return [(section.heading, section.text) for section in split_issue_sections(body)]


def words(text: str) -> list[str]:
    return WORD_RE.findall(text)


def body_hash(text: str) -> str:
    return hashlib.sha256(text.encode("utf-8")).hexdigest()[:16]


def parse_year(value: str) -> int | None:
    match = re.match(r"(\d{4})", str(value or ""))
    return int(match.group(1)) if match else None


def plain_text(markdown: str) -> str:
    text = re.sub(r"!\[[^\]]*\]\([^)]+\)", "", markdown)
    text = re.sub(r"\[([^\]]+)\]\([^)]+\)", r"\1", text)
    text = re.sub(r"`([^`]+)`", r"\1", text)
    text = re.sub(r"^#{1,6}\s+", "", text, flags=re.M)
    text = re.sub(r"[*_>~]+", "", text)
    return " ".join(text.split())


def summarize_text(text: str, max_chars: int = 420) -> str:
    clean = plain_text(text)
    if len(clean) <= max_chars:
        return clean
    sentences = SENTENCE_RE.split(clean)
    summary = ""
    for sentence in sentences:
        if len(summary) + len(sentence) + 1 > max_chars:
            break
        summary = f"{summary} {sentence}".strip()
    return summary or clean[:max_chars].rsplit(" ", 1)[0]


def detect_topics(subject: str, body: str, limit: int = 6) -> list[str]:
    tokens = [token.lower() for token in words(f"{subject} {body[:12000]}")]
    counts = {}
    token_set = set(tokens)
    for topic, keywords in TOPIC_KEYWORDS.items():
        score = sum(tokens.count(keyword) for keyword in keywords if keyword in token_set)
        minimum = 1 if topic in {"AI and agents", "Open web and RSS"} else 2
        if score >= minimum:
            counts[topic] = score
    return [
        topic for topic, _ in sorted(counts.items(), key=lambda item: (-item[1], item[0]))[:limit]
    ]


# Link targets, tags and bare URLs: not the passage's words. A micro.blog or
# feedburner URL is not the passage talking about blogs or feeds.
_TOPIC_NOISE_RE = re.compile(r"\]\([^)]*\)|<[^>]+>|https?://\S+|www\.\S+", re.I)
_MICRO_BLOG_RE = re.compile(r"\bmicro\.blog\b", re.I)


def chunk_topics(heading: str, text: str) -> list[str]:
    """The clusters one passage is about, from its own heading and text.

    Chunks used to inherit their issue's clusters, and since every issue
    links a micro.blog or blog URL, "Open web and RSS" sat on 8,856 of 8,895
    Weekly Thing chunks, so search_archive's topic filter barely narrowed
    (QA 2026-09-30, retrieval Q1). This is the same detector and the same
    nine clusters as ``detect_topics``, read over the passage's prose (link
    targets and tags removed), with "micro.blog" read as the ``microblog``
    keyword that the word split would otherwise break in two."""
    prose = _MICRO_BLOG_RE.sub("microblog", _TOPIC_NOISE_RE.sub(" ", f"{heading}\n{text}"))
    return detect_topics("", prose)


# --- media / currently / journal extraction (2026-08 tool audit) ----------
#
# The audit exercise showed three brute-force patterns in the agent: photo
# questions (no media index), "what was Jamie reading/playing" (Currently
# sections unexploited), and journal-vs-blog duplicate retrieval. These
# build-time extractors close them. None of them alter chunk text, so the
# id-keyed embed cache stays warm.

_MEDIA_IMG_TAG_RE = re.compile(r"<img\b[^>]*>", re.I | re.S)
# A Journal entry's own permalink, in every era's style: "Thursday @ 9:28 PM",
# "Sep 24, 2023 at 3:40 PM" (with a narrow no-break space), "2018-05-04 4:47
# PM", "5:25 PM", and the 2017 "→". Links with any other text are Jamie
# pointing at an older post, not an entry.
_JOURNAL_ENTRY_LINK_RE = re.compile(
    r"\[(?:[^\]]*\d{1,2}:\d{2}[\s\u202f]*[AP]M[^\]]*|\s*→\s*)\]"
    r"\((https?://(?:www\.|micro\.)?thingelstad\.com/\d{4}/\d{2}/\d{2}/[^)\s]+)\)",
    re.I,
)
# The colon sits inside the bold ("**Reading:**") in most issues and outside
# it ("**Dining**:") in ten lines from 2022-2025, which were dropped until
# QA 2026-09-30 (ingest F12).
_CURRENTLY_LINE_RE = re.compile(
    r"^\*\*([A-Za-z][A-Za-z ]{2,20})(?::\*\*|\*\*\s*:)\s*(.+)$",
    re.M,
)


def _img_attr(tag: str, name: str) -> str:
    match = re.search(rf"\b{name}\s*=\s*([\"\'])(.*?)\1", tag, re.I | re.S)
    return " ".join((match.group(2) if match else "").split())


def extract_images(text: str) -> list[dict[str, str]]:
    """Every image in a markdown/html body as {url, alt}, attribute-order
    agnostic, covering both <img> tags and markdown image syntax."""
    out = []
    for tag in _MEDIA_IMG_TAG_RE.findall(text or ""):
        url = _img_attr(tag, "src")
        if url:
            out.append({"url": url, "alt": _img_attr(tag, "alt")})
    for link in markdown_links(text or ""):
        if link.kind == "image":
            out.append({"url": link.url, "alt": " ".join(link.label.split())})
    return out


def _media_context(text: str, url: str, max_chars: int = 240) -> str:
    """The prose nearest an image: the first non-empty, non-image line after
    the tag (issue captions follow images), falling back to the line before."""
    lines = (text or "").split("\n")
    index = next(
        (
            i
            for i, line in enumerate(lines)
            if url in line and ("<img" in line or line.strip().startswith("!["))
        ),
        None,
    )
    if index is None:
        return ""

    def usable(line: str) -> bool:
        clean = line.strip()
        return bool(clean) and "<img" not in clean and not clean.startswith("![") and clean != "---"

    for line in lines[index + 1 :]:
        if usable(line):
            return plain_text(line)[:max_chars]
    for line in reversed(lines[:index]):
        if usable(line):
            return plain_text(line)[:max_chars]
    return ""


def annotate_media_descriptions(corpus: dict[str, Any], sidecar_path: Path) -> int:
    """Merge vision descriptions (pipeline/corpus/describe_media.py) into the
    corpus's media entries by URL. The description is machine metadata kept
    BESIDE Jamie's authored alt and the caption context, never replacing
    either - it exists so an image is findable and describable even when the
    authored text says nothing (92% of Weekly Thing media had empty alt when
    this landed). Returns how many entries gained a description."""
    if not sidecar_path.exists():
        return 0
    sidecar = json.loads(sidecar_path.read_text())
    annotated = 0
    for entry in corpus.get("media", []) or []:
        record = sidecar.get(str(entry.get("url") or ""))
        description = (record or {}).get("description")
        if description:
            entry["description"] = description
            annotated += 1
    return annotated


def journal_post_urls(section_text: str) -> list[str]:
    """Canonical blog-post URLs of the journal entries inside a Journal
    section chunk - the day-at-time entry links. Retrieval uses these to
    dedupe a journal chunk against the standalone blog posts it reprints."""
    return list(
        dict.fromkeys(
            _canonical_blog_url(url) for url in _JOURNAL_ENTRY_LINK_RE.findall(section_text or "")
        )
    )


def _canonical_blog_url(url: str) -> str:
    """A thingelstad.com post URL as the blog corpus spells it: https, www,
    no query or fragment (``?ref=weekly-thing``)."""
    match = _BLOG_PERMALINK_RE.search(url)
    if not match:
        return url
    return "https://www.thingelstad.com/" + re.split(r"[?#]", match.group(1), maxsplit=1)[0]


_H1_H2_RE = re.compile(r"^(#{1,2}\s+.+?)\s*$", re.M)
_H3_RE = re.compile(r"^###\s+(.+?)\s*$", re.M)
_READING_ERA_RE = re.compile(r"^(?:now\s+)?reading\b", re.I)


def extract_now_reading_entries(body: str) -> list[dict[str, Any]]:
    """Reading entries from the 2017-2018 "Now Reading 📚" sections (WT8-77),
    the era before "**Reading:**" lines in a Currently section: one per H3
    book (the H2's own lines, a cover image or a bare link, belong to the
    first), or the section itself when it has no H3. Same shape as
    ``extract_currently_entries``, kind "reading"."""
    entries: list[dict[str, Any]] = []
    parts = _H1_H2_RE.split(body or "")
    for heading, block in zip(parts[1::2], parts[2::2], strict=True):
        if not heading.startswith("## "):
            continue
        name = clean_heading(heading[3:])
        if section_family(name) != "Currently" or not _READING_ERA_RE.match(name):
            continue
        books = _H3_RE.split(block)
        lead, pairs = books[0], list(zip(books[1::2], books[2::2], strict=True))
        if not pairs:
            lead, pairs = "", [("", books[0])]
        for index, (title, text) in enumerate(pairs):
            source = f"{lead if index == 0 else ''}\n\n{title}\n\n{text}"
            links: dict[str, dict[str, str]] = {}
            for text_, url, _ in _body_links(source):
                links.setdefault(url, {"title": text_ or url, "url": url})
            # A bare store link above the blurb is a link, not the entry's words.
            prose = plain_text(f"{clean_heading(title)}\n\n{text}")
            prose = " ".join(re.sub(r"<?https?://\S+", " ", prose).split())
            if prose or links:
                entries.append({"kind": "reading", "text": prose[:400], "links": [*links.values()]})
    return entries


def extract_currently_entries(section_text: str) -> list[dict[str, Any]]:
    """Typed entries from a Currently section: **Reading:** / **Playing:** /
    **Watching:** / **Listening:** lines with their links and prose."""
    entries = []
    for label, rest in _CURRENTLY_LINE_RE.findall(section_text or ""):
        links = [
            {"title": link_label_text(link.label) or link.url, "url": link.url}
            for link in markdown_links(rest)
            if link.kind != "image"
        ]
        entries.append(
            {
                "kind": label.strip().lower(),
                "text": plain_text(rest)[:400],
                "links": links,
            }
        )
    return entries


# What a family's text is, whatever the era called its heading. A family
# missing here (Intro, and the one-off H2s that are their own family) falls
# back to reading the heading.
FAMILY_CONTENT_KINDS = {
    "Featured": "links",
    "Notable": "links",
    "Briefly": "links",
    "FYI": "links",
    "App": "links",
    "Journal": "personal",
    "Currently": "personal",
    "Photo": "personal",
    "Fortune": "meta",
    "Reply All": "meta",
    "Straw Poll": "meta",
    "Give Back": "meta",
    "Support": "meta",
    "Yearly Thing": "essay",
}


def content_kind(section: str, family: str | None = None) -> str:
    if family in FAMILY_CONTENT_KINDS:
        return FAMILY_CONTENT_KINDS[family]
    name = section.lower()
    if any(part in name for part in ("journal", "photo", "currently")):
        return "personal"
    if any(part in name for part in ("links", "briefly", "fortune")):
        return "links"
    if any(part in name for part in ("give back", "promotion", "sponsor")):
        return "meta"
    return "essay" if name in EVERGREEN_SECTIONS or len(name.split()) <= 4 else "reference"


# Voice provenance: whose words each part of a chunk is. Everything is
# Jamie's except blockquoted lines (someone else's words, quoted), the
# headline link of a link item (a page's own title), and a Fortune (a
# fortune-cookie line). Spans partition the chunk text; the embed input is
# untouched, so no chunk re-embeds.
LINK_FAMILIES = {"Featured", "Notable", "Briefly", "FYI", "App"}
QUOTED_FAMILIES = {"Fortune"}
_BLOCKQUOTE_LINE_RE = re.compile(r"^[ \t]*>.*$", re.M)
# A line that is only a link: "- [Title](url) domain.com", "[Title](url)".
_LINK_LINE_RE = re.compile(
    r"^[ \t]*(?:[-*+][ \t]+)?(?:\*\*)?\[[^\]\n]*\]\([^)\s]+\)(?:\*\*)?(?:[ \t]+[\w.-]+\.\w+)?[ \t]*$",
    re.M,
)
# A Briefly headline: "{commentary} → **[Title](url)**".
_BOLD_LINK_RE = re.compile(r"\*\*\[[^\]\n]*\]\([^)\s]+\)\*\*")


def voice_spans(text: str, family: str | None = None) -> list[dict[str, Any]]:
    """``[{voice, start, end}]`` covering ``text`` end to end: ``jamie``,
    ``quoted`` or ``link``. A run of whitespace between two marks joins the
    span before it, so consecutive quoted lines are one span."""
    if not text:
        return []
    if family in QUOTED_FAMILIES:
        return [{"voice": "quoted", "start": 0, "end": len(text)}]
    marks = [(m.start(), m.end(), "quoted") for m in _BLOCKQUOTE_LINE_RE.finditer(text)]
    if family in LINK_FAMILIES:
        marks += [(m.start(), m.end(), "link") for m in _LINK_LINE_RE.finditer(text)]
        marks += [(m.start(), m.end(), "link") for m in _BOLD_LINK_RE.finditer(text)]
    spans: list[dict[str, Any]] = []

    def push(start: int, end: int, voice: str) -> None:
        if end <= start:
            return
        if spans and spans[-1]["voice"] == voice and spans[-1]["end"] == start:
            spans[-1]["end"] = end
        else:
            spans.append({"voice": voice, "start": start, "end": end})

    cursor = 0
    for start, end, voice in sorted(marks):
        if start < cursor:
            continue
        gap = text[cursor:start]
        if spans and not gap.strip():
            push(cursor, start, spans[-1]["voice"])
        else:
            push(cursor, start, "jamie")
        push(start, end, voice)
        cursor = end
    push(cursor, len(text), "jamie")
    return spans


def time_sensitivity(subject: str, body: str) -> str:
    text = f"{subject} {body[:4000]}".lower()
    if any(
        term in text
        for term in ("today", "this week", "beta", "launch", "announced", "now available")
    ):
        return "time_sensitive"
    if any(term in text for term in ("principle", "framework", "lesson", "why", "how to")):
        return "evergreen"
    return "mixed"


def key_points_for_sections(sections: list[tuple[str, str]], limit: int = 5) -> list[str]:
    points = []
    for section, section_body in sections:
        if section.lower() in {"issue", "promotion", "give back"}:
            continue
        point = summarize_text(section_body, max_chars=180)
        if point:
            points.append(f"{section}: {point}")
        if len(points) == limit:
            break
    return points


# Where a chunk's overlap lead-in may start: after a line break, or after a
# sentence's closing punctuation (and any closing quote, bracket or emphasis).
_OVERLAP_BOUNDARY_RE = re.compile(r"\n+|[.!?][\"'’”)\]*_]*[ \t]+")
# Spans an overlap must never start inside: markdown links/images, HTML tags.
_OVERLAP_ATOMIC_RE = re.compile(r"!?\[[^\]]*\]\([^)]*\)|<[^>]*>")


def _overlap_tail(text: str, overlap_words: int) -> str:
    """The lead-in the next chunk repeats: the whole sentences (or lines) that
    fall inside ``text``'s last ``overlap_words`` words, copied VERBATIM, so
    it is always an exact suffix of ``text``. With no sentence boundary in
    that window it starts at the cut word, moved past any link or tag the
    cut lands inside.

    This used to be ``" ".join(words(text)[-overlap_words:])``: a
    de-punctuated token soup (URLs became "https weekly thingelstad com")
    stored as the first paragraph of the next chunk, which search results
    and lenses then showed as passage text (review 2026-09-29, defect 15).
    """
    tokens = list(WORD_RE.finditer(text))
    if not tokens or overlap_words <= 0:
        return ""
    cut = tokens[max(len(tokens) - overlap_words, 0)].start()
    if cut == tokens[0].start():
        return text.strip()
    atomic = [match.span() for match in _OVERLAP_ATOMIC_RE.finditer(text)]

    def inside_atomic(position: int) -> bool:
        return any(start < position < end for start, end in atomic)

    for boundary in _OVERLAP_BOUNDARY_RE.finditer(text):
        start = boundary.end()
        if start >= cut and not inside_atomic(start) and WORD_RE.search(text, start):
            return text[start:].strip()
    for start, end in atomic:
        if start < cut < end:
            cut = end
    return text[cut:].strip()


def _cut_points(text: str, pattern: re.Pattern[str], atomic: list[tuple[int, int]]) -> list:
    """``(start, end)`` of the whitespace after each ``pattern`` boundary in
    ``text`` (a sentence end, a line break, a space), skipping any that falls
    inside an ``atomic`` span (a markdown link or HTML tag)."""
    points = []
    for match in pattern.finditer(text):
        raw = match.group(0)
        start = match.start() + len(raw.rstrip())
        if start <= 0 or match.end() >= len(text) or start == match.end():
            continue
        if any(left < start < right for left, right in atomic):
            continue
        points.append((start, match.end()))
    return points


_SPACE_CUT_RE = re.compile(r"[ \t]+")


def _fitting_units(paragraph: str, max_chars: int) -> list[tuple[str, str]]:
    """``paragraph`` as ``[(separator, piece)]`` pieces of at most
    ``max_chars``. A paragraph that fits is one piece. One that does not is
    cut at its sentence ends and line breaks, then a piece still too long at
    its spaces (outside links and tags first), then, as a last resort, every
    ``max_chars``. Each separator is the whitespace the cut removed, so the
    pieces rejoin to the paragraph verbatim."""
    units: list[tuple[str, str]] = [("\n\n", paragraph)]
    for pattern, keep_atomic in (
        (_OVERLAP_BOUNDARY_RE, True),
        (_SPACE_CUT_RE, True),
        (_SPACE_CUT_RE, False),
    ):
        refined: list[tuple[str, str]] = []
        for separator, piece in units:
            if len(piece) <= max_chars:
                refined.append((separator, piece))
                continue
            atomic = (
                [match.span() for match in _OVERLAP_ATOMIC_RE.finditer(piece)]
                if keep_atomic
                else []
            )
            cursor = 0
            for start, end in _cut_points(piece, pattern, atomic):
                if start == cursor:  # back-to-back boundaries: one wider separator
                    separator, cursor = separator + piece[start:end], end
                    continue
                refined.append((separator, piece[cursor:start]))
                separator, cursor = piece[start:end], end
            refined.append((separator, piece[cursor:]))
        units = refined
    fitted: list[tuple[str, str]] = []
    for separator, piece in units:
        for offset in range(0, len(piece), max_chars):
            fitted.append((separator if offset == 0 else "", piece[offset : offset + max_chars]))
    return fitted


def _fitting_overlap(previous: str, overlap_words: int, room: int) -> str:
    """The longest overlap lead-in of at most ``overlap_words`` words that
    fits in ``room`` characters, or "" when none does."""
    for count in range(overlap_words, 0, -10):
        overlap = _overlap_tail(previous, count)
        if len(overlap) <= room:
            return overlap
    return ""


def chunk_section(
    text: str,
    max_words: int = 400,
    overlap_words: int = 60,
    max_chars: int | None = None,
) -> list[str]:
    """Split ``text`` into chunks of at most ``max_words`` words, each after
    the first opening with a verbatim overlap lead-in from the one before.

    ``max_chars`` caps a chunk's length in characters too: it is the room
    the chunk's text has inside one embedding input, which Bedrock cuts at
    2,048 characters (``embed_text_budget``). Before the cap, 8.7% of Weekly
    Thing words sat past that cut in no embedding at all (QA 2026-09-30,
    ingest F1). The cap only changes a section that produced an overlong
    chunk: a chunk that fits is built exactly as before, so its id stays."""
    tokens = words(text)
    if len(tokens) <= max_words and (max_chars is None or len(text.strip()) <= max_chars):
        return [text.strip()] if text.strip() else []

    paragraphs = [p.strip() for p in re.split(r"\n{2,}", text) if p.strip()]
    units = (
        [unit for paragraph in paragraphs for unit in _fitting_units(paragraph, max_chars)]
        if max_chars
        else [("\n\n", paragraph) for paragraph in paragraphs]
    )
    chunks: list[str] = []
    current = ""
    current_words = 0

    for separator, unit in units:
        count = len(words(unit))
        too_long = max_chars is not None and len(current) + len(separator) + len(unit) > max_chars
        if current and (current_words + count > max_words or too_long):
            chunks.append(current.strip())
            overlap = _overlap_tail(chunks[-1], overlap_words)
            if max_chars is not None and len(overlap) + 2 + len(unit) > max_chars:
                overlap = _fitting_overlap(chunks[-1], overlap_words, max_chars - 2 - len(unit))
            current = f"{overlap}\n\n{unit}" if overlap else unit
            current_words = len(words(overlap)) + count
        else:
            current = f"{current}{separator}{unit}" if current else unit
            current_words += count

    if current:
        chunks.append(current.strip())
    return chunks


# --- non-archive sources -------------------------------------------------
#
# Thingy's questions aren't all "what did you say about X in issue N?".
# Origin / cadence / "what's the supporting membership" / FAQ-shaped
# questions land just as often. The archive corpus didn't carry any of
# that, so Thingy would guess. We bring three structured site sources
# into the same embedded corpus alongside issue chunks so semantic
# retrieval surfaces them naturally:
#
#   - data/site/about.njk           → site:about           page-prose chunks
#   - data/site/support.njk         → site:members         page-prose chunks
#   - data/site/_data/support.json  → site:nonprofit-history structured-fact chunk
#   - apps/librarian/lambda/shared/faq.json → faq:<section>:<index> chunks
#
# **Privacy fence:** these chunks must never carry subscriber/member
# counts. The site renders ``stats.premium_subscriber_count`` on
# /members/, but we deliberately don't read ``_data/stats.json`` or
# ``_data/supportTotals.js`` here, and a unit test scans the final
# corpus to confirm no count field leaked in (would fail loud if a
# future njk template change embedded a subscriber count directly
# into about.njk / support.njk).

# Banned strings that must not appear anywhere in the corpus chunks.
# subscriber_count + premium_subscriber_count are stats.json field names;
# matching them anywhere catches the obvious "we accidentally rendered
# the stats block into the page" regression.
CORPUS_PRIVACY_DENYLIST: tuple[str, ...] = (
    "subscriber_count",
    "premium_subscriber_count",
    "stats.subscriber",
    "stats.premium",
)

_FRONTMATTER_FENCE_RE = re.compile(r"\A---\s*\n.*?\n---\s*\n", re.S)
_NJK_BLOCK_RE = re.compile(r"\{%.*?%\}", re.S)
_NJK_EXPR_RE = re.compile(r"\{\{(.*?)\}\}", re.S)
_HTML_TAG_RE = re.compile(r"<[^>]+>")
_HTML_ENTITY_MAP = {
    "&mdash;": "—",
    "&ndash;": "–",
    "&hellip;": "…",
    "&lsquo;": "'",
    "&rsquo;": "'",
    "&ldquo;": '"',
    "&rdquo;": '"',
    "&amp;": "&",
    "&nbsp;": " ",
    "&middot;": "·",
    "&rarr;": "→",
}


def _resolve_njk_expr(raw: str, replacements: dict[str, str]) -> str:
    """Best-effort resolution of a ``{{ var | filter }}`` expression.
    Returns the matched replacement if the variable name is in
    ``replacements``; otherwise returns ``""`` so the surrounding prose
    reads cleanly without template debris.
    """
    bare = raw.split("|", 1)[0].strip()
    return replacements.get(bare, "")


def _strip_njk_page(text: str, *, replacements: dict[str, str] | None = None) -> str:
    """Reduce a Nunjucks template (frontmatter + HTML + ``{% %}`` /
    ``{{ }}`` syntax) to plain prose suitable for embedding.

    Frontmatter is dropped wholesale. ``{% %}`` control-flow tags are
    deleted (their bodies stay — control flow doesn't change the visible
    text for these pages). ``{{ expr }}`` expressions are resolved via
    ``replacements`` if known (e.g. ``yearlyPrice → "48"``) and dropped
    otherwise. HTML tags get stripped; basic entities decoded; whitespace
    normalized.
    """
    replacements = replacements or {}
    s = _FRONTMATTER_FENCE_RE.sub("", text or "")
    s = _NJK_BLOCK_RE.sub("", s)
    s = _NJK_EXPR_RE.sub(lambda m: _resolve_njk_expr(m.group(1), replacements), s)
    # Strip inline <script>…</script> + <style>…</style> blocks before
    # tag-stripping so their bodies don't leak into the text.
    s = re.sub(r"<(script|style)\b[^>]*>.*?</\1>", "", s, flags=re.I | re.S)
    s = _HTML_TAG_RE.sub(" ", s)
    for entity, decoded in _HTML_ENTITY_MAP.items():
        s = s.replace(entity, decoded)
    s = re.sub(r"&#x?\d+;", "", s)
    # Collapse runs of whitespace to single spaces, then re-introduce
    # paragraph breaks where the source had blank lines.
    s = re.sub(r"[ \t]+", " ", s)
    s = re.sub(r"\n\s*\n+", "\n\n", s)
    s = re.sub(r"^[ \t]+|[ \t]+$", "", s, flags=re.M)
    return s.strip()


def _site_page_chunks(
    *,
    site_dir: Path,
    issue_count: int,
    years_active: int,
    latest_issue_number: Any,
) -> list[dict[str, Any]]:
    """Build site_page chunks for /about/ + /members/ from the .njk
    templates and the structured support.json data.

    Each chunk lands with ``source_kind: "site_page"``, no
    ``issue_number`` (these aren't issues), and a stable id like
    ``site:about:0`` so the embedded corpus is reproducible across
    builds (same input → same id → cache hit on the deploy reupload).
    """
    out: list[dict[str, Any]] = []
    replacements = {
        "archiveStats.yearsActive": str(years_active),
        "collections.issuesByDate[0].data.number": str(latest_issue_number or ""),
        "issueCount": str(issue_count),
        "yearsActive": str(years_active),
        "support.yearly_price": "",  # filled in members loader below
    }

    about_path = site_dir / "about.njk"
    if about_path.exists():
        prose = _strip_njk_page(about_path.read_text(encoding="utf-8"), replacements=replacements)
        budget = embed_text_budget(
            {"issue_number": None, "subject": "About the Weekly Thing", "section": "About"}
        )
        for index, chunk_text in enumerate(chunk_section(prose, max_chars=budget)):
            out.append(
                {
                    "id": f"site:about:{index}",
                    "issue_number": None,
                    "subject": "About the Weekly Thing",
                    "publish_date": None,
                    "issue_year": None,
                    "url": "/about/",
                    "section": "About",
                    "text": chunk_text,
                    "word_count": len(words(chunk_text)),
                    "content_kind": "site_page",
                    "topics": [],
                    "source_kind": "site_page",
                }
            )

    support_data_path = site_dir / "_data" / "support.json"
    support_data: dict[str, Any] = {}
    if support_data_path.exists():
        try:
            support_data = json.loads(support_data_path.read_text(encoding="utf-8"))
        except ValueError, TypeError:
            support_data = {}
    yearly_price = support_data.get("yearly_price") or 48
    replacements["support.yearly_price"] = str(yearly_price)

    members_path = site_dir / "support.njk"
    if members_path.exists():
        prose = _strip_njk_page(members_path.read_text(encoding="utf-8"), replacements=replacements)
        budget = embed_text_budget(
            {
                "issue_number": None,
                "subject": "Supporting Membership",
                "section": "Supporting Membership",
            }
        )
        for index, chunk_text in enumerate(chunk_section(prose, max_chars=budget)):
            out.append(
                {
                    "id": f"site:members:{index}",
                    "issue_number": None,
                    "subject": "Supporting Membership",
                    "publish_date": None,
                    "issue_year": None,
                    "url": "/members/",
                    "section": "Supporting Membership",
                    "text": chunk_text,
                    "word_count": len(words(chunk_text)),
                    "content_kind": "site_page",
                    "topics": [],
                    "source_kind": "site_page",
                }
            )

    # Render the structured nonprofit history into its own chunk —
    # concrete, year-by-year, easy for Thingy to quote.
    if support_data:
        history_parts: list[str] = []
        current = support_data.get("current") or {}
        if current.get("nonprofit"):
            history_parts.append(
                f"The {current.get('year_label') or current.get('year') or 'current'} "
                f"Supporting Member nonprofit is {current['nonprofit']}"
                + (f" — {current['description']}" if current.get("description") else "")
                + "."
            )
        past = support_data.get("past") or []
        if past:
            history_parts.append("Past nonprofits supported by Weekly Thing Supporting Members:")
            for org in past:
                if not isinstance(org, dict):
                    continue
                year_label = org.get("year_label") or org.get("year")
                name = org.get("nonprofit") or org.get("short_name")
                if not name:
                    continue
                amount = org.get("amount_raised")
                amount_str = (
                    f" (~${amount:,.0f} raised)" if isinstance(amount, (int, float)) else ""
                )
                history_parts.append(f"- {year_label}: {name}{amount_str}")
        if history_parts:
            text = "\n".join(history_parts)
            out.append(
                {
                    "id": "site:nonprofit-history:0",
                    "issue_number": None,
                    "subject": "Supporting Member nonprofit history",
                    "publish_date": None,
                    "issue_year": None,
                    "url": "/members/",
                    "section": "Supporting Member nonprofit history",
                    "text": text,
                    "word_count": len(words(text)),
                    "content_kind": "site_page",
                    "topics": [],
                    "source_kind": "site_page",
                }
            )

    return out


def _faq_chunks(*, faq_path: Path, issue_count: int, years_active: int) -> list[dict[str, Any]]:
    """Bring the FAQ into the embedded corpus so semantic retrieval can
    surface entries without depending on Thingy picking the explicit
    ``search_faq`` tool. Each FAQ entry becomes one chunk.
    """
    if not faq_path.exists():
        return []
    try:
        data = json.loads(faq_path.read_text(encoding="utf-8"))
    except ValueError, TypeError:
        return []
    out: list[dict[str, Any]] = []
    replacements = {
        "issueCount": str(issue_count),
        "yearsActive": str(years_active),
    }
    for section in data.get("sections", []) or []:
        if not isinstance(section, dict):
            continue
        title = str(section.get("title") or "").strip()
        if not title:
            continue
        section_slug = re.sub(r"[^a-z0-9]+", "-", title.lower()).strip("-") or "section"
        for index, entry in enumerate(section.get("entries", []) or []):
            if not isinstance(entry, dict):
                continue
            q = str(entry.get("question") or "").strip()
            a = str(entry.get("answer") or "").strip()
            if not q or not a:
                continue
            # Resolve known interpolations from the JSON strings.
            a = _NJK_EXPR_RE.sub(lambda m: _resolve_njk_expr(m.group(1), replacements), a)
            text = f"Q. {q}\n\nA. {a}"
            out.append(
                {
                    "id": f"faq:{section_slug}:{index}",
                    "issue_number": None,
                    "subject": f"FAQ — {title}",
                    "publish_date": None,
                    "issue_year": None,
                    "url": "/faq/",
                    "section": title,
                    "text": text,
                    "word_count": len(words(text)),
                    "content_kind": "faq",
                    "topics": [],
                    "source_kind": "faq",
                }
            )
    return out


def _privacy_audit(chunks: list[dict[str, Any]]) -> None:
    """Defensive: refuse to ship a corpus that carries subscriber-count
    text. Catches a regression where a future njk template change might
    embed ``stats.subscriber_count`` into about.njk / support.njk."""
    for chunk in chunks:
        text = str(chunk.get("text") or "")
        lowered = text.lower()
        for needle in CORPUS_PRIVACY_DENYLIST:
            if needle.lower() in lowered:
                raise RuntimeError(
                    f"Privacy denylist hit in chunk {chunk.get('id')!r}: "
                    f"{needle!r} appears in text. Refusing to build corpus."
                )


def chunk_id(issue_number: Any, section: str, index: int, text: str) -> str:
    digest = hashlib.sha256(
        f"{issue_number}\0{section}\0{index}\0{text}".encode("utf-8")
    ).hexdigest()
    return digest[:16]


def build_corpus(
    archive_dir: Path = ARCHIVE_DIR,
    include_issue_bodies: bool = False,
    site_dir: Path | None = None,
    faq_path: Path | None = None,
    blog_dir: Path | None = None,
    podcast_dir: Path | None = None,
) -> dict[str, Any]:
    chunks: list[dict[str, Any]] = []
    media: list[dict[str, Any]] = []
    currently: list[dict[str, Any]] = []
    issues = []
    links: list[dict[str, Any]] = []
    topic_index: dict[str, dict[str, Any]] = {}
    targets: dict[str, Any] = {
        "weekly": weekly_issue_lookup(archive_dir),
        "blog": blog_post_lookup(blog_dir or BLOG_DIR),
        "podcast": podcast_episode_lookup(podcast_dir or PODCAST_DIR),
    }
    for path in sorted(
        archive_dir.glob("*/archive.md"), key=lambda p: issue_sort_key(p.parent.name)
    ):
        metadata, body = read_issue(path)
        body = strip_thingy_blocks(body)
        number = metadata.get("number") or path.parent.name
        subject = metadata.get("subject") or f"Weekly Thing {number}"
        publish_date = metadata.get("publish_date") or ""
        url = f"/archive/{number}/"
        issue_word_count = len(words(body))
        split = split_issue_sections(body)
        sections = [(section.heading, section.text) for section in split]
        topics = detect_topics(subject, body)
        issue_summary = {
            "abstract": summarize_text(body),
            "key_points": key_points_for_sections(sections),
            "topics": topics,
            "time_sensitivity": time_sensitivity(subject, body),
        }
        issue_sections = [
            {
                "name": section.heading,
                "section_family": section.family,
                "text": section.text,
                "word_count": len(words(section.text)),
            }
            for section in split
        ]
        issue_links = []
        link_fields = {
            "issue_number": number,
            "subject": subject,
            "publish_date": publish_date,
            "issue_year": parse_year(publish_date),
            "issue_url": url,
        }
        for link in metadata.get("links") or []:
            if not isinstance(link, dict):
                continue
            record = {
                **link_fields,
                "section": link.get("section"),
                "section_family": section_family(link.get("section")) or link.get("section"),
                "url": link.get("url"),
                "domain": link.get("domain"),
                "text": link.get("text") or link.get("title") or link.get("heading_context"),
                "heading_context": link.get("heading_context"),
                "context": link.get("context") or link.get("heading_context"),
                "link_role": "headline",
            }
            if include_issue_bodies:
                record.update(resolve_link_target(str(link.get("url") or ""), **targets))
                issue_links.append(record)
                links.append(record)
        if include_issue_bodies:
            seen_urls = {str(link.get("url") or "") for link in issue_links}
            for section in split:
                for record in issue_body_links(section, skip_urls=seen_urls):
                    record = {**link_fields, **record}
                    record.update(resolve_link_target(record["url"], **targets))
                    issue_links.append(record)
                    links.append(record)
        issues.append(
            {
                "number": number,
                "subject": subject,
                "publish_date": publish_date,
                "issue_year": parse_year(publish_date),
                "url": url,
                **({"description": metadata["description"]} if metadata.get("description") else {}),
                "word_count": issue_word_count,
                "body_hash": body_hash(body),
                "summary": issue_summary,
                "topics": topics,
            }
        )
        if include_issue_bodies:
            issues[-1]["body"] = body
            issues[-1]["sections"] = issue_sections
            issues[-1]["domains"] = metadata.get("domains") or []
            issues[-1]["links"] = issue_links
        for topic in topics:
            entry = topic_index.setdefault(
                topic,
                {
                    "name": topic,
                    "description": f"Archive material related to {topic.lower()}.",
                    "first_seen": publish_date,
                    "last_seen": publish_date,
                    "issue_numbers": [],
                    "representative_issues": [],
                    "related_topics": [],
                },
            )
            entry["issue_numbers"].append(number)
            if publish_date and (not entry["first_seen"] or publish_date < entry["first_seen"]):
                entry["first_seen"] = publish_date
            if publish_date and publish_date > entry["last_seen"]:
                entry["last_seen"] = publish_date

        for image in extract_images(body):
            media.append(
                {
                    "url": image["url"],
                    "alt": image["alt"],
                    "context": _media_context(body, image["url"]),
                    "source_kind": "weekly_thing",
                    "issue_number": number,
                    "subject": subject,
                    "source_url": url,
                    "publish_date": publish_date,
                }
            )
        issue_fields = {
            "issue_number": number,
            "subject": subject,
            "publish_date": publish_date,
            "issue_url": url,
        }
        for entry in extract_now_reading_entries(body):
            currently.append({**entry, **issue_fields})
        for issue_section in split:
            section, family, section_body = (
                issue_section.heading,
                issue_section.family,
                issue_section.text,
            )
            if section.strip().lower() == "currently":
                for entry in extract_currently_entries(section_body):
                    currently.append({**entry, **issue_fields})
            budget = embed_text_budget(
                {
                    "issue_number": number,
                    "subject": subject,
                    "publish_date": publish_date,
                    "issue_abstract": issue_summary["abstract"],
                    "section": section,
                }
            )
            for index, chunk_text in enumerate(chunk_section(section_body, max_chars=budget)):
                if TEMPLATE_LEAK_RE.search(chunk_text):
                    raise RuntimeError(
                        f"Template/generated content leaked into corpus for issue {number}"
                    )
                # The blog post's own URL where the corpus has it, so the
                # retrieval dedupe joins even when that URL is on another host.
                chunk_journal_urls = list(
                    dict.fromkeys(
                        targets["blog"].get(_blog_target_path(u) or "", {}).get("url") or u
                        for u in journal_post_urls(chunk_text)
                    )
                )
                chunks.append(
                    {
                        "id": chunk_id(number, section, index, chunk_text),
                        "issue_number": number,
                        "subject": subject,
                        "publish_date": publish_date,
                        "issue_year": parse_year(publish_date),
                        "url": url,
                        "section": section,
                        "section_family": family,
                        "text": chunk_text,
                        "spans": voice_spans(chunk_text, family),
                        "word_count": len(words(chunk_text)),
                        "content_kind": content_kind(section, family),
                        # The passage's own clusters; the issue's stay on
                        # the issue record (list_content filters on those).
                        "topics": chunk_topics(section, chunk_text),
                        "issue_abstract": issue_summary["abstract"],
                        "source_kind": "chunk",
                        **({"journal_post_urls": chunk_journal_urls} if chunk_journal_urls else {}),
                    }
                )

    for entry in topic_index.values():
        entry["representative_issues"] = entry["issue_numbers"][-8:]
        related = set()
        for issue in issues:
            if entry["name"] in issue.get("topics", []):
                related.update(topic for topic in issue.get("topics", []) if topic != entry["name"])
        entry["related_topics"] = sorted(related)[:8]

    # Non-archive sources — origin / membership / FAQ. Embedded alongside
    # issue chunks so semantic retrieval surfaces them naturally without
    # needing dedicated tools. See ``_site_page_chunks`` / ``_faq_chunks``
    # docstrings for the privacy boundary (no subscriber counts).
    years_active = 0
    issue_years = [
        parse_year(issue.get("publish_date")) for issue in issues if issue.get("publish_date")
    ]
    issue_years = [y for y in issue_years if y]
    if issue_years:
        years_active = max(issue_years) - min(issue_years) + 1
    latest_issue_number = issues[-1]["number"] if issues else None
    if site_dir is not None or SITE_DIR.exists():
        site_chunks = _site_page_chunks(
            site_dir=site_dir or SITE_DIR,
            issue_count=len(issues),
            years_active=years_active,
            latest_issue_number=latest_issue_number,
        )
        chunks.extend(site_chunks)
    if faq_path is not None or FAQ_PATH.exists():
        faq_chunks = _faq_chunks(
            faq_path=faq_path or FAQ_PATH,
            issue_count=len(issues),
            years_active=years_active,
        )
        chunks.extend(faq_chunks)
    _privacy_audit(chunks)

    return {
        "version": 2,
        "source": "data/issues",
        "generated_at": datetime.now(timezone.utc).isoformat().replace("+00:00", "Z"),
        "embedding_model": None,
        "embed_recipe": EMBED_RECIPE_VERSION,
        "issue_count": len(issues),
        "chunk_count": len(chunks),
        "link_count": len(links),
        "issues": issues,
        "topics": sorted(topic_index.values(), key=lambda item: item["name"]),
        "links": links,
        "chunks": chunks,
        "media": media,
        "currently": currently,
    }


# --- blog corpus ---------------------------------------------------------
#
# Jamie's 20-year thingelstad.com blog is a *separate* corpus from the
# Weekly Thing issue archive above. Two corpus objects give hard scope
# isolation: the WT corpus stays byte-identical to today, the blog corpus
# lazy-loads only when a reader's scope asks for it, and "both" is the only
# path that mixes them (a query-time rerank). The builder reuses the same
# chunk primitives (``chunk_section`` / ``content_kind`` / ``words`` /
# ``_privacy_audit``) so the embed + upload tooling is shared verbatim.

# A thingelstad.com (or legacy micro.thingelstad.com) permalink, capturing
# the ``YYYY/MM/DD/slug`` path that uniquely identifies a post. Used both to
# scan issue Journal sections for blog back-references and to normalize a
# blog post's own URL to the same key.
_BLOG_PERMALINK_RE = re.compile(
    r"https?://(?:www\.|micro\.)?thingelstad\.com/(\d{4}/\d{2}/\d{2}/[^\s)\"'<>]+)",
    re.I,
)
# An ``<img …>`` tag's alt text — inlined into the embedding text so photo
# descriptions are searchable (the canonical store keeps the full tag).
_BLOG_IMG_ALT_RE = re.compile(r'<img\b[^>]*?\balt\s*=\s*(["\'])(.*?)\1[^>]*?>', re.I | re.S)
_BLOG_IMG_BARE_RE = re.compile(r"<img\b[^>]*?>", re.I | re.S)
_BLOG_HTML_LINK_RE = re.compile(
    r'<a\s+[^>]*href=["\']([^"\']+)["\'][^>]*>(.*?)</a>',
    re.I | re.S,
)
_BLOG_INTERNAL_DOMAINS = {"thingelstad.com", "www.thingelstad.com", "micro.thingelstad.com"}
_CROSS_SOURCE_BY_DOMAIN = {
    "weekly.thingelstad.com": "weekly_thing",
    "another.thingelstad.com": "podcast",
}
_BLOG_HOSTLIKE_PATH_RE = re.compile(r"/(?:www\.)?[a-z0-9-]+\.[a-z]{2,}(?:/|$)", re.I)


def _is_thingelstad_domain(domain: str) -> bool:
    return domain == "thingelstad.com" or domain.endswith(".thingelstad.com")


def _normalize_blog_path(path_part: str) -> str:
    """``2026/05/23/slug.html`` → ``2026/05/23/slug`` — the cross-corpus key
    shared by an issue's Journal back-reference and the blog post itself
    (host/scheme/``.html`` and any ``?ref=weekly-thing`` query dropped)."""
    p = re.split(r"[?#]", path_part.strip(), maxsplit=1)[0].rstrip("/")
    return re.sub(r"\.html?$", "", p, flags=re.I)


def journal_blog_xref(archive_dir: Path = ARCHIVE_DIR) -> dict[str, list[Any]]:
    """Scan issue archive bodies for thingelstad.com blog back-references
    (the Journal section links to ``thingelstad.com/YYYY/MM/DD/slug`` inline,
    *not* via the curated ``links[]``), returning
    ``{normalized_blog_path: [issue_number, …]}`` so the blog builder can
    stamp ``also_in_issues`` on the matching blog chunks. One-directional
    (blog→issue) for v1: the issue already links to the blog inline."""
    xref: dict[str, set] = {}
    for path in sorted(
        archive_dir.glob("*/archive.md"), key=lambda p: issue_sort_key(p.parent.name)
    ):
        metadata, body = read_issue(path)
        body = strip_thingy_blocks(body)
        number = metadata.get("number") or path.parent.name
        for match in _BLOG_PERMALINK_RE.finditer(body):
            xref.setdefault(_normalize_blog_path(match.group(1)), set()).add(number)
    return {key: sorted(nums, key=issue_sort_key) for key, nums in xref.items()}


# --- cross-source link targets ------------------------------------------
#
# A link to one of Jamie's own sources resolves to its archive id, so a link
# record can say "this is WT186" or "this is blog post 6034145" rather than
# only a URL. Weekly issues are linked by number (/archive/351/) or by their
# old slug (/archive/weekly-thing-186-blockchain-pairing-sharding/).

_WEEKLY_ARCHIVE_PATH_RE = re.compile(r"^/archive/([^/?#]+)/?$", re.I)
_WEEKLY_SLUG_NUMBER_RE = re.compile(r"^weekly-thing-(\d+)(?:-|$)", re.I)
_BLOG_PERMALINK_PATH_RE = re.compile(r"^/\d{4}/\d{2}/\d{2}/[^/]+")


def weekly_issue_lookup(archive_dir: Path = ARCHIVE_DIR) -> dict[str, Any]:
    """``{slug or number (lower-case): issue number}`` for every issue."""
    lookup: dict[str, Any] = {}
    for path in archive_dir.glob("*/archive.md"):
        metadata, _body = read_issue(path)
        number = metadata.get("number") or path.parent.name
        lookup[str(number).lower()] = number
        if metadata.get("slug"):
            lookup[str(metadata["slug"]).lower()] = number
    return lookup


def blog_post_lookup(blog_dir: Path = BLOG_DIR) -> dict[str, dict[str, Any]]:
    """``{normalised blog path: {microblog_id, url, subject}}`` from the post
    front matter alone. Keyed on the date path whatever the host, since the
    2017 posts' canonical URLs are on jthingelstad.micro.blog."""
    lookup: dict[str, dict[str, Any]] = {}
    for path in blog_dir.rglob("*.md"):
        match = FRONTMATTER_RE.match(path.read_text(encoding="utf-8"))
        metadata = (yaml.safe_load(match.group(1)) if match else None) or {}
        post_path = urlparse(str(metadata.get("url") or "")).path
        target = (
            _normalize_blog_path(post_path.lstrip("/"))
            if _BLOG_PERMALINK_PATH_RE.match(post_path)
            else None
        )
        if target and metadata.get("microblog_id") is not None:
            lookup[target] = {
                "microblog_id": metadata["microblog_id"],
                "url": metadata.get("url"),
                "subject": str(metadata.get("title") or "").strip(),
            }
    return lookup


def podcast_episode_lookup(podcast_dir: Path = PODCAST_DIR) -> dict[str, dict[str, Any]]:
    """``{normalised episode path: {episode_number, url, subject}}``."""
    lookup: dict[str, dict[str, Any]] = {}
    for path in podcast_dir.glob("*.json"):
        episode = json.loads(path.read_text(encoding="utf-8"))
        url = str(episode.get("url") or "")
        key = _normalize_blog_path(urlparse(url).path.lstrip("/")) if url else ""
        if key:
            lookup[key] = {
                "episode_number": episode.get("number"),
                "url": url,
                "subject": str(episode.get("title") or "").strip(),
            }
    return lookup


def resolve_link_target(
    url: str,
    *,
    weekly: dict[str, Any] | None = None,
    blog: dict[str, dict[str, Any]] | None = None,
    podcast: dict[str, dict[str, Any]] | None = None,
) -> dict[str, Any]:
    """Target fields for a link to one of Jamie's sources: ``target_source_kind``,
    ``target_resolved`` and the target's number or id. Empty for a link
    anywhere else, including a source's home page (weekly.thingelstad.com/)."""
    try:
        parsed = urlparse(url)
    except ValueError:
        return {}
    host = (parsed.hostname or "").lower()
    if host == "weekly.thingelstad.com":
        match = _WEEKLY_ARCHIVE_PATH_RE.match(parsed.path or "")
        if not match:
            return {}
        slug = match.group(1).lower()
        number = (weekly or {}).get(slug)
        if number is None and (numbered := _WEEKLY_SLUG_NUMBER_RE.match(slug)):
            number = (weekly or {}).get(numbered.group(1))
        record: dict[str, Any] = {
            "target_source_kind": "weekly_thing",
            "target_resolved": number is not None,
        }
        if number is not None:
            record["target_issue_number"] = number
        return record
    if host == "another.thingelstad.com":
        if not _BLOG_PERMALINK_PATH_RE.match(parsed.path or ""):
            return {}
        episode = (podcast or {}).get(_normalize_blog_path((parsed.path or "").lstrip("/")))
        record = {"target_source_kind": "podcast", "target_resolved": episode is not None}
        if episode:
            record["target_episode_number"] = episode["episode_number"]
            record["target_subject"] = episode["subject"]
        return record
    if host in _BLOG_INTERNAL_DOMAINS:
        target_path = _blog_target_path(url)
        if not target_path:
            return {}
        post = (blog or {}).get(target_path)
        record = {
            "target_source_kind": "blog",
            "target_resolved": post is not None,
            "target_blog_path": target_path,
        }
        if post:
            record["target_microblog_id"] = post["microblog_id"]
            record["target_post_url"] = post["url"]
            if post["subject"]:
                record["target_subject"] = post["subject"]
        return record
    return {}


# Link roles on an issue's link records. ``headline`` is the item a link
# section is built from (the front-matter links, plus a heading link the
# front matter missed); ``journal`` is any link inside a Journal; everything
# else is ``commentary``: the links Jamie drops into what he writes.


def _link_paragraph(text: str, position: int, max_chars: int = 240) -> str:
    start = text.rfind("\n\n", 0, position)
    end = text.find("\n\n", position)
    paragraph = text[start + 2 if start >= 0 else 0 : end if end >= 0 else len(text)]
    return plain_text(paragraph).strip()[:max_chars]


def issue_body_links(
    section: IssueSection,
    *,
    skip_urls: set[str],
) -> list[dict[str, Any]]:
    """Link records for one split section, minus ``skip_urls`` (the issue's
    front-matter links and anything an earlier section already gave), which
    it extends. Records carry ``link_role`` and the section's family; the
    caller adds the issue fields and targets."""
    records: list[dict[str, Any]] = []

    def add(text: str, url: str, role: str, context: str) -> None:
        if not url or url.startswith(("#", "mailto:")) or url in skip_urls:
            return
        try:
            domain = (urlparse(url).hostname or "").lower()
        except ValueError:
            return
        if not domain:
            return
        skip_urls.add(url)
        records.append(
            {
                "section": section.parent,
                "section_family": section.family,
                "heading_context": section.heading if section.heading != section.parent else None,
                "url": url,
                "domain": domain,
                "text": text or domain,
                "context": context,
                "link_role": role,
            }
        )

    body_role = "journal" if section.family == "Journal" else "commentary"
    heading_role = "headline" if section.family in LINK_FAMILIES else body_role
    for text, url, _ in _body_links(section.raw_heading or ""):
        add(text, url, heading_role, section.heading)
    for text, url, position in _body_links(section.text):
        add(text, url, body_role, _link_paragraph(section.text, position))
    return records


def _blog_embed_text(body: str) -> str:
    """Reduce a native-markdown blog post to embedding-friendly text: inline
    each ``<img>``'s alt text (good photo-search signal), drop any remaining
    HTML tags, normalize whitespace. Markdown links are left intact, matching
    how issue chunks are embedded."""
    s = _BLOG_IMG_ALT_RE.sub(lambda m: f" {m.group(2).strip()} ", body or "")
    s = _BLOG_IMG_BARE_RE.sub(" ", s)
    s = _HTML_TAG_RE.sub(" ", s)
    s = re.sub(r"[ \t]+", " ", s)
    s = re.sub(r"\n\s*\n+", "\n\n", s)
    return s.strip()


def _short_label(text: str, max_words: int = 12) -> str:
    """A readable citation label for an untitled micropost — the first few
    words of its plain text."""
    tokens = plain_text(text).split()
    label = " ".join(tokens[:max_words])
    return label + ("…" if len(tokens) > max_words else "")


def _body_links(body: str) -> list[tuple[str, str, int]]:
    """``(text, url, position)`` for every link in a markdown/HTML body, text
    already plain: markdown links first (a linked image ``[![alt](img)](target)``
    is a link to its target, text the alt), then ``<a>`` anchors, then
    ``<autolinks>`` and bare URLs, whose text is the URL. Images are media,
    not links (``extract_images``)."""
    scanned = markdown_links(body or "")
    links = [
        (link_label_text(link.label), link.url, link.start)
        for link in scanned
        if link.kind == "inline"
    ]
    links += [
        (plain_text(_HTML_TAG_RE.sub(" ", match.group(2))), match.group(1).strip(), match.start())
        for match in _BLOG_HTML_LINK_RE.finditer(body or "")
    ]
    links += [
        (link.url, link.url, link.start) for link in scanned if link.kind in {"autolink", "bare"}
    ]
    return links


def _markdown_html_links(body: str) -> list[tuple[str, str]]:
    return [(text, url) for text, url, _ in _body_links(body)]


def _blog_target_path(url: str) -> str | None:
    match = _BLOG_PERMALINK_RE.search(url or "")
    if not match:
        return None
    return _normalize_blog_path(match.group(1))


def _blog_link_category(
    parsed: Any,
    *,
    link_kind: str,
    target_post: dict[str, Any] | None,
    target_source_kind: str | None = None,
) -> str:
    if target_source_kind in {"blog", "weekly_thing", "podcast"}:
        return "cross_source"
    if target_source_kind == "site":
        return "internal_site"
    if link_kind == "external":
        return "external"
    path = parsed.path or ""
    if target_post:
        return "resolved_post"
    if path.startswith("/uploads/"):
        return "upload_asset"
    if path.startswith("/collections/"):
        return "collection_page"
    if _BLOG_HOSTLIKE_PATH_RE.search(path):
        return "malformed_internal"
    host = (parsed.hostname or "").lower()
    if _is_thingelstad_domain(host) and host not in _BLOG_INTERNAL_DOMAINS:
        return "internal_site"
    return "internal_unresolved"


def _blog_outbound_links(
    body: str,
    *,
    microblog_id: Any,
    subject: str,
    publish_date: str | None,
    post_kind: str,
    post_url: str,
    post_lookup: dict[str, dict[str, Any]],
    weekly_lookup: dict[str, Any] | None = None,
    podcast_lookup: dict[str, dict[str, Any]] | None = None,
) -> list[dict[str, Any]]:
    """Extract post-level outbound links from native blog markdown/HTML.

    Unlike Weekly Thing's curated-link extractor, every non-image markdown
    link and HTML anchor in a blog post is editorial context. The resulting
    records mirror the issue corpus's top-level ``links`` enough for the same
    domain tools to query them, while keeping the source post URL separate
    from the linked destination URL.
    """
    records: list[dict[str, Any]] = []
    seen_urls: set[str] = set()

    def add(text: str, link_url: str) -> None:
        if not link_url or link_url.startswith("#") or link_url.startswith("mailto:"):
            return
        resolved_url = urljoin(post_url, link_url)
        try:
            parsed = urlparse(resolved_url)
        except Exception:
            return
        domain = (parsed.hostname or "").lower()
        if not domain or resolved_url in seen_urls:
            return
        seen_urls.add(resolved_url)
        target_path = _blog_target_path(resolved_url)
        target_post = post_lookup.get(target_path or "")
        target_source_kind = _CROSS_SOURCE_BY_DOMAIN.get(domain)
        if (
            not target_source_kind
            and domain not in _BLOG_INTERNAL_DOMAINS
            and _is_thingelstad_domain(domain)
        ):
            target_source_kind = "site"
        link_kind = "internal" if _is_thingelstad_domain(domain) else "external"
        link_category = _blog_link_category(
            parsed,
            link_kind=link_kind,
            target_post=target_post,
            target_source_kind=target_source_kind,
        )
        record = {
            "source_kind": "blog",
            "microblog_id": microblog_id,
            "post_url": post_url,
            "post_subject": subject,
            "subject": subject,
            "publish_date": publish_date,
            "post_year": parse_year(publish_date),
            "issue_year": parse_year(publish_date),
            "post_kind": post_kind,
            "section": "Micropost" if post_kind == "micropost" else "Blog post",
            "url": resolved_url,
            "domain": domain,
            "text": text,
            "context": text,
            "link_kind": link_kind,
            "link_category": link_category,
            "target_resolved": bool(target_post),
        }
        if target_source_kind:
            record["target_source_kind"] = target_source_kind
        if target_path:
            record["target_blog_path"] = target_path
        if target_post:
            record["target_source_kind"] = "blog"
            record["target_microblog_id"] = target_post.get("microblog_id")
            record["target_post_url"] = target_post.get("url")
            record["target_subject"] = target_post.get("subject")
            record["target_publish_date"] = target_post.get("publish_date")
        elif target_source_kind in {"weekly_thing", "podcast"}:
            record.update(
                resolve_link_target(resolved_url, weekly=weekly_lookup, podcast=podcast_lookup)
            )
        records.append(record)

    for text, link_url in _markdown_html_links(body):
        add(text, link_url)
    return records


def build_blog_corpus(
    blog_dir: Path = BLOG_DIR,
    archive_dir: Path = ARCHIVE_DIR,
    include_xref: bool = True,
    podcast_dir: Path = PODCAST_DIR,
) -> dict[str, Any]:
    """Build the blog corpus from ``data/blog/posts/**/*.md``. One chunk per
    ``chunk_section`` piece, ``source_kind: "blog"``, content-deterministic id
    ``blog:{microblog_id}:{index}:{body_hash}``. The corpus also carries a
    post-level outbound-link graph (``links`` / ``link_count`` plus chunk
    ``domains``) so Thingy can answer domain/link questions over the blog the
    same way it can over Weekly Thing. Posts that also appear in a Weekly Thing
    Journal get an ``also_in_issues`` cross-reference."""
    xref = journal_blog_xref(archive_dir) if include_xref else {}
    weekly_lookup = weekly_issue_lookup(archive_dir) if include_xref else {}
    podcast_lookup = podcast_episode_lookup(podcast_dir)
    chunks: list[dict[str, Any]] = []
    media: list[dict[str, Any]] = []
    posts: list[dict[str, Any]] = []
    links: list[dict[str, Any]] = []
    post_inputs: list[dict[str, Any]] = []
    post_lookup: dict[str, dict[str, Any]] = {}
    post_count = 0
    for path in sorted(blog_dir.rglob("*.md")):
        metadata, body = read_issue(path)
        microblog_id = metadata.get("microblog_id")
        if microblog_id is None:
            raise RuntimeError(f"{path} is missing microblog_id in front matter")
        url = str(metadata.get("url") or "").strip()
        title = str(metadata.get("title") or "").strip()
        post_kind = str(metadata.get("post_kind") or "post").strip()
        section = "Micropost" if post_kind == "micropost" else "Blog post"
        match = _BLOG_PERMALINK_RE.search(url)
        publish_date = None
        if match:
            publish_date = "-".join(match.group(1).split("/")[:3])
        if not publish_date:
            publish_date = str(metadata.get("published") or "")[:10] or None
        also_in_issues = (
            xref.get(_normalize_blog_path(url.split("//", 1)[-1].split("/", 1)[-1]))
            if url
            else None
        )
        if not also_in_issues and match:
            also_in_issues = xref.get(_normalize_blog_path(match.group(1)))
        embed_text = _blog_embed_text(body)
        if not embed_text:
            continue
        subject = title or _short_label(embed_text)
        post_input = {
            "body": body,
            "microblog_id": microblog_id,
            "url": url,
            "subject": subject,
            "publish_date": publish_date,
            "post_kind": post_kind,
            "section": section,
            "also_in_issues": also_in_issues,
            "embed_text": embed_text,
            "published": str(metadata.get("published") or "") or None,
            "categories": [str(c) for c in metadata.get("categories") or [] if str(c).strip()],
        }
        target_path = _blog_target_path(url)
        if target_path:
            post_lookup[target_path] = {
                "microblog_id": microblog_id,
                "url": url,
                "subject": subject,
                "publish_date": publish_date,
            }
        post_inputs.append(post_input)

    for post_input in post_inputs:
        post_count += 1
        body = post_input["body"]
        microblog_id = post_input["microblog_id"]
        url = post_input["url"]
        subject = post_input["subject"]
        publish_date = post_input["publish_date"]
        post_kind = post_input["post_kind"]
        section = post_input["section"]
        also_in_issues = post_input["also_in_issues"]
        embed_text = post_input["embed_text"]
        post_links = _blog_outbound_links(
            body,
            microblog_id=microblog_id,
            subject=subject,
            publish_date=publish_date,
            post_kind=post_kind,
            post_url=url,
            post_lookup=post_lookup,
            weekly_lookup=weekly_lookup,
            podcast_lookup=podcast_lookup,
        )
        post_domains = extract_domains(post_links)
        links.extend(post_links)
        post_record = {
            "microblog_id": microblog_id,
            "subject": subject,
            "publish_date": publish_date,
            "post_year": parse_year(publish_date),
            "url": url,
            "post_kind": post_kind,
            "body_hash": body_hash(body),
            "domains": post_domains,
            "links": post_links,
        }
        if post_input["published"]:
            post_record["published"] = post_input["published"]
        if post_input["categories"]:
            post_record["categories"] = post_input["categories"]
        if also_in_issues:
            post_record["also_in_issues"] = also_in_issues
        posts.append(post_record)
        for image in extract_images(body):
            media.append(
                {
                    "url": image["url"],
                    "alt": image["alt"],
                    "context": _media_context(body, image["url"]) or plain_text(embed_text)[:240],
                    "source_kind": "blog",
                    # The post's own key: six permalinks are shared by
                    # fourteen posts, so source_url alone names the wrong one.
                    "microblog_id": microblog_id,
                    "subject": subject,
                    "source_url": url,
                    "publish_date": publish_date,
                }
            )
        budget = embed_text_budget(
            {
                "source_kind": "blog",
                "publish_date": publish_date,
                "subject": subject,
                "section": section,
            }
        )
        for index, chunk_text in enumerate(chunk_section(embed_text, max_chars=budget)):
            # Content-deterministic id (text hash suffix): when a post's body is
            # edited in place (alt-text inlined, de-wrap, typo fix) without
            # changing its chunk count, the id still changes — so the
            # incremental embed cache (keyed on id) re-embeds it instead of
            # reusing the stale vector. Readable mbid:index prefix kept for
            # debugging. Mirrors the issue corpus's content-hashed `chunk_id`.
            chunk = {
                "id": f"blog:{microblog_id}:{index}:{body_hash(chunk_text)}",
                "microblog_id": microblog_id,
                "issue_number": None,
                "subject": subject,
                "publish_date": publish_date,
                "issue_year": parse_year(publish_date),
                "url": url,
                "section": section,
                "text": chunk_text,
                "spans": voice_spans(chunk_text),
                "word_count": len(words(chunk_text)),
                "content_kind": "blog",
                "topics": chunk_topics(subject, chunk_text),
                "source_kind": "blog",
                "domains": post_domains,
            }
            if also_in_issues:
                chunk["also_in_issues"] = also_in_issues
            chunks.append(chunk)

    _privacy_audit(chunks)

    return {
        "version": 2,
        "source": "data/blog/posts",
        "generated_at": datetime.now(timezone.utc).isoformat().replace("+00:00", "Z"),
        "embedding_model": None,
        "embed_recipe": EMBED_RECIPE_VERSION,
        "issue_count": 0,
        "post_count": post_count,
        "chunk_count": len(chunks),
        "link_count": len(links),
        "issues": [],
        "media": media,
        "posts": posts,
        "topics": [],
        "links": links,
        "chunks": chunks,
    }


# --- podcast corpus ------------------------------------------------------
#
# Podcast transcripts are kept in their own corpus for the same reason the
# blog is: source isolation and lazy loading. Another Thing is a small corpus
# today, but keeping it separate means a podcast-only question never crowds
# the Weekly Thing search space and old callers keep their WT defaults.


def _episode_number_label(value: Any) -> str:
    try:
        return f"{int(value):03d}"
    except TypeError, ValueError:
        return str(value or "").strip()


def _podcast_show_note_links(
    episode: dict[str, Any],
    notes: str,
    *,
    subject: str,
    publish_date: str | None,
) -> list[dict[str, Any]]:
    records: list[dict[str, Any]] = []
    seen_urls: set[str] = set()
    episode_url = str(episode.get("url") or "").strip()
    for text, link_url in _markdown_html_links(notes):
        if not link_url or link_url.startswith("#") or link_url.startswith("mailto:"):
            continue
        resolved_url = urljoin(episode_url, link_url)
        try:
            parsed = urlparse(resolved_url)
        except Exception:
            continue
        domain = (parsed.hostname or "").lower()
        if not domain or resolved_url in seen_urls:
            continue
        seen_urls.add(resolved_url)
        target_source_kind = None
        if domain in {"thingelstad.com", "www.thingelstad.com", "micro.thingelstad.com"}:
            target_source_kind = "blog"
        elif domain == "weekly.thingelstad.com":
            target_source_kind = "weekly_thing"
        elif domain != "another.thingelstad.com" and domain.endswith("thingelstad.com"):
            target_source_kind = "site"
        link_kind = (
            "internal" if domain == "another.thingelstad.com" or target_source_kind else "external"
        )
        records.append(
            {
                "source_kind": "podcast",
                "show": episode.get("show") or "Another Thing",
                "podcast": "another-thing",
                "episode_number": episode.get("number"),
                "episode_url": episode_url,
                "subject": subject,
                "publish_date": publish_date,
                "issue_year": parse_year(publish_date),
                "section": "Show notes",
                "url": resolved_url,
                "domain": domain,
                "text": text,
                "context": text,
                "link_kind": link_kind,
                "link_category": "cross_source"
                if target_source_kind in {"blog", "weekly_thing", "podcast"}
                else "internal_site"
                if link_kind == "internal"
                else "external",
                "target_resolved": False,
                **({"target_source_kind": target_source_kind} if target_source_kind else {}),
            }
        )
    return records


def build_podcast_corpus(podcast_dir: Path = PODCAST_DIR) -> dict[str, Any]:
    """Build the Another Thing podcast corpus from normalized episode JSON.

    ``pipeline/podcast/import_another_thing.py`` writes one JSON record per
    episode. Transcript chunks use ``source_kind: "podcast"`` and ids like
    ``podcast:another-thing:001:0:{hash}``.
    """
    chunks: list[dict[str, Any]] = []
    episodes: list[dict[str, Any]] = []
    links: list[dict[str, Any]] = []
    episode_count = 0
    for path in sorted(podcast_dir.glob("*.json")):
        episode = json.loads(path.read_text(encoding="utf-8"))
        transcript = str(episode.get("transcript_text") or "").strip()
        notes = str(episode.get("notes_markdown") or "").strip()
        if not transcript and not notes:
            continue
        episode_count += 1
        number = episode.get("number")
        number_label = _episode_number_label(number)
        subject = str(episode.get("title") or f"Episode {number_label}").strip()
        publish_date = str(episode.get("publish_date") or "")[:10] or None
        episode_links = _podcast_show_note_links(
            episode, notes, subject=subject, publish_date=publish_date
        )
        episode_domains = extract_domains(episode_links)
        links.extend(episode_links)
        episode_sections = []
        if transcript:
            episode_sections.append(
                {
                    "name": "Transcript",
                    "word_count": len(words(transcript)),
                    "content_kind": "podcast_transcript",
                }
            )
        if notes:
            episode_sections.append(
                {
                    "name": "Show notes",
                    "word_count": len(words(notes)),
                    "content_kind": "podcast_notes",
                }
            )
        episodes.append(
            {
                "number": number,
                "show": episode.get("show") or "Another Thing",
                "podcast": "another-thing",
                "subject": subject,
                "publish_date": publish_date,
                "issue_year": parse_year(publish_date),
                "url": episode.get("url"),
                "transcript_url": episode.get("transcript_url"),
                "audio_url": episode.get("audio_url"),
                "summary": episode.get("summary") or "",
                "body_hash": body_hash("\n\n".join(part for part in [transcript, notes] if part)),
                "sections": episode_sections,
                "domains": episode_domains,
                "links": episode_links,
            }
        )
        base = {
            "issue_number": None,
            "source_kind": "podcast",
            "show": episode.get("show") or "Another Thing",
            "podcast": "another-thing",
            "episode_number": number,
            "subject": subject,
            "publish_date": publish_date,
            "issue_year": parse_year(publish_date),
            "url": episode.get("url"),
            "transcript_url": episode.get("transcript_url"),
            "audio_url": episode.get("audio_url"),
            "summary": episode.get("summary") or "",
            "topics": [],
            "domains": episode_domains,
        }
        sections = []
        if transcript:
            sections.append(("Transcript", "podcast_transcript", transcript))
        if notes:
            sections.append(("Show notes", "podcast_notes", notes))
        for section, content_kind, text in sections:
            budget = embed_text_budget({**base, "section": section})
            for index, chunk_text in enumerate(
                chunk_section(text, max_words=320, overlap_words=55, max_chars=budget)
            ):
                chunks.append(
                    {
                        **base,
                        "id": f"podcast:another-thing:{number_label}:{section.lower().replace(' ', '-')}:"
                        f"{index}:{body_hash(chunk_text)}",
                        "section": section,
                        "content_kind": content_kind,
                        "text": chunk_text,
                        "topics": chunk_topics(subject, chunk_text),
                        "word_count": len(words(chunk_text)),
                    }
                )

    _privacy_audit(chunks)

    return {
        "version": 2,
        "source": "data/podcast/another-thing/episodes",
        "generated_at": datetime.now(timezone.utc).isoformat().replace("+00:00", "Z"),
        "embedding_model": None,
        "embed_recipe": EMBED_RECIPE_VERSION,
        "issue_count": 0,
        "episode_count": episode_count,
        "chunk_count": len(chunks),
        "link_count": len(links),
        "issues": [],
        "episodes": episodes,
        "topics": [],
        "links": links,
        "chunks": chunks,
    }


# Version of the embed-input construction below. The incremental embed cache
# is keyed on chunk id, and ids hash only the chunk TEXT - so an edit to the
# header lines handed to the embedding model would silently reuse stale
# vectors. Bump this whenever _embed_input changes shape; the uploader treats
# a mismatch as a cold cache and re-embeds everything (a few dollars, minutes).
EMBED_RECIPE_VERSION = 2


def _embed_header(chunk: dict[str, Any]) -> list[str]:
    """The header lines ``_embed_input`` puts above a chunk's text."""
    if chunk.get("source_kind") == "blog":
        lines = [f"thingelstad.com blog — {chunk.get('publish_date') or ''}".rstrip(" —")]
        if chunk.get("subject"):
            lines.append(f"Post: {chunk['subject']}")
        lines.append(f"Section: {chunk['section']}")
        return lines
    if chunk.get("source_kind") == "podcast":
        episode = chunk.get("episode_number")
        label = f"Episode {episode}" if episode is not None else "Episode"
        lines = [f"Another Thing podcast — {chunk.get('publish_date') or ''}".rstrip(" —")]
        if chunk.get("subject"):
            lines.append(f"{label}: {chunk['subject']}")
        lines.append(f"Section: {chunk['section']}")
        if chunk.get("summary"):
            lines.append(f"Summary: {chunk['summary']}")
        return lines
    lines = [f"Weekly Thing #{chunk['issue_number']}: {chunk['subject']}"]
    if chunk.get("publish_date"):
        lines.append(f"Published: {chunk['publish_date']}")
    # Contextual retrieval: most chunks are one short section, so the issue
    # abstract is what situates them. The issue-level Topics line is gone -
    # every chunk in an issue carried the same six topics, which polluted
    # the embedding with identical non-content tokens.
    if chunk.get("issue_abstract"):
        lines.append(f"Issue summary: {chunk['issue_abstract']}")
    lines.append(f"Section: {chunk['section']}")
    return lines


def _embed_input(chunk: dict[str, Any]) -> str:
    """The text handed to the embedding model for one chunk. Blog chunks get a
    blog-shaped header; everything else keeps the original Weekly-Thing header
    verbatim so existing corpus.json embed inputs stay byte-identical (cache
    stays warm)."""
    return "\n".join([*_embed_header(chunk), chunk["text"]])


# The fewest characters a chunk's text is ever given, so a freak header
# cannot reduce chunking to slivers. No real header comes close: the longest
# Weekly Thing one, issue summary and all, is under 700 characters.
MIN_EMBED_TEXT_CHARS = 1000


def embed_text_budget(chunk: dict[str, Any]) -> int:
    """How many characters of text fit in ``chunk``'s embedding input below
    the header ``_embed_input`` puts above it. Bedrock's Cohere embed takes
    at most 2,048 characters a text, and text past that is in no embedding.
    ``chunk`` needs only the header fields, not the text."""
    header = "\n".join(_embed_header(chunk))
    return max(COHERE_EMBED_MAX_TEXT_CHARS - len(header) - 1, MIN_EMBED_TEXT_CHARS)


def fetch_bedrock_embeddings(
    inputs: list[str], model: str, input_type: str = "search_document"
) -> list[list[float]]:
    # The builders size every chunk to fit (embed_text_budget), so this cut
    # is a backstop that should never bite. Say so when it does: text past
    # it is in no embedding.
    over = sum(1 for text in inputs if len(text) > COHERE_EMBED_MAX_TEXT_CHARS)
    if over:
        print(
            f"embed_input_truncated: {over} of {len(inputs)} inputs over "
            f"{COHERE_EMBED_MAX_TEXT_CHARS} chars; their tails are in no embedding"
        )
    inputs = [text[:COHERE_EMBED_MAX_TEXT_CHARS] for text in inputs]
    response = boto3.client("bedrock-runtime").invoke_model(
        modelId=model,
        body=json.dumps({"texts": inputs, "input_type": input_type, "truncate": "END"}),
        accept="application/json",
        contentType="application/json",
    )
    data = json.loads(response["body"].read())
    embeddings = data.get("embeddings") or []
    if len(embeddings) != len(inputs):
        raise RuntimeError(
            f"Bedrock returned {len(embeddings)} embeddings for {len(inputs)} inputs"
        )
    return embeddings


def add_bedrock_embeddings(
    corpus: dict[str, Any], model: str, dimensions: int, batch_size: int = 96
) -> None:
    load_dotenv()
    chunks = corpus["chunks"]
    # Only embed chunks that don't already have an embedding. Callers (the
    # upload script) may have hydrated unchanged chunks from a previous
    # corpus's cache before calling this; those chunks already carry their
    # vector and re-embedding them would just burn money.
    pending = [chunk for chunk in chunks if not chunk.get("embedding")]
    if not pending:
        # All embeddings reused from cache. Set model/dimensions from
        # whatever's already on the chunks.
        corpus["embedding_model"] = model
        if chunks and chunks[0].get("embedding"):
            corpus["embedding_dimensions"] = len(chunks[0]["embedding"])
        else:
            corpus["embedding_dimensions"] = dimensions
        print(f"All {len(chunks)} chunk embeddings reused from cache; skipped Bedrock call.")
        return
    for start in range(0, len(pending), batch_size):
        batch = pending[start : start + batch_size]
        inputs = [_embed_input(chunk) for chunk in batch]
        embeddings = fetch_bedrock_embeddings(inputs, model)
        for chunk, embedding in zip(batch, embeddings):
            chunk["embedding"] = embedding
        print(f"Embedded chunks {start + 1}-{start + len(batch)} of {len(pending)} pending")
    corpus["embedding_model"] = model
    # Derive dimensions from a chunk that has an embedding (works whether
    # this batch added new ones or all were already cached).
    sample = next((c for c in chunks if c.get("embedding")), None)
    corpus["embedding_dimensions"] = len(sample["embedding"]) if sample else dimensions
